### ISSUE TITLE
AttributeError: 'TaxiBJTrainer' object has no attribute 'data'

### ISSUE THREAD

**Issue by ucalyptus** [metrofun/E3D-LSTM#2]
**Link to notebook**
[Click here](https://colab.research.google.com/drive/1jWuszK3ukcpocITOXRxygVIEpwgSAENi)

**Steps to reproduce this issue:**
1.`cd /content/E3D-LSTM/src/`
2.`sys.path.append('/content/E3D-LSTM/src')`
3. `!python -m trainer`

**Error Stack Trace**
`Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/E3D-LSTM/src/trainer.py", line 177, in <module>
    trainer.resume_train()
  File "/content/E3D-LSTM/src/trainer.py", line 132, in resume_train
    train_dataloader = self.get_trainloader(self.data[:-672])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'TaxiBJTrainer' object has no attribute 'data'`

**Comment by ucalyptus** [comment]
cc: @metrofun

**Comment by YutianPangASU** [comment]
I was having the same issue as yours. Please check your version capability of package h5py. For instance, make sure the utils.h5_virtual_file() function works smoothly on your machine.

**Comment by ucalyptus** [comment]
@ypang6 I see, it's been a long time since trying out this proj. will try and let u know
